---
- name: 'Installing docker through ansible'
  hosts: localhost
  become: true
  vars:
    docker_user: "yousafkhamza"
    docker_password: "Yousafkh@7"
    repo_url: "https://github.com/yousafkhamza/nodejs-dockerfile.git"
    repo_dest: "/var/repository/"
    repo: "yousafkhamza/dapp:1"
  tasks:

    - name: "PIP Installation"
      yum:
        name: pip
        state: present
        
    - name: "Depandancy Task-Install Dokcer-py"
      pip:
        name: docker-py
        state: present

    - name: "Docker Installtion"
      yum:
        name: docker
        state: present

    - name: "Docker Service start and Enable"
      service:
        name: docker
        state: restarted
        enabled: true

    - name: "Build-Step - Cloning Repository"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
      register: repo_status

    - name: "Build-Step - Login to remote Repository"
      when: repo_status.changed == true
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: "Build Docker image from Dockerfile"
      docker_image:
        build:
          path: "{{ repo_dest }}"
        name: myimage
        tag: v1
        repository: "{{ repo }}"
        push: yes
        source: build